### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by akamob** [minwoo0611/pcd_to_las#1]
Hi, Thank you for the great work.

I met the following error:
```
CMake Error at CMakeLists.txt:9 (FIND_PACKAGE):
  By not providing "FindlibLAS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libLAS", but
  CMake did not find one.

  Could not find a package configuration file provided by "libLAS" with any
  of the following names:

    libLASConfig.cmake
    liblas-config.cmake

  Add the installation prefix of "libLAS" to CMAKE_PREFIX_PATH or set
  "libLAS_DIR" to a directory containing one of the above files.  If "libLAS"
  provides a separate development package or SDK, be sure it has been
  installed.
```

May i have your suggestions to fix this problem?
Any help is much appreciated.

**Comment by Pranav15112000** [comment]
Hi akamob, 

Were you able to fix this issue? If no, did you use any other pcd to las converter?

**Comment by minwoo0611** [comment]
Hello,

I apologize for the delayed reply.

Regarding the error you encountered with CMake and libLAS: the issue stems from CMake's inability to locate the libLAS library. To resolve this, you need to first build libLAS. You can find the necessary files and instructions at [libLAS's GitHub repository](https://github.com/libLAS/libLAS).

Alternatively, if you're looking for a simpler solution, especially if you're working with a smaller amount of data, you might want to consider using CloudCompare. This software allows you to load PCD files and then export them as LAS files. CloudCompare is user-friendly and could be a more convenient option for handling point cloud data.

I hope this helps in fixing the problem. Let me know if you need any further assistance!
